import type { NextPage } from 'next'
import Head from 'next/head'
import TextareaAutosize from 'react-textarea-autosize';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen">
        <div className="flex justify-center">
          <div className="flex flex-col justify-center items-center">
            <h1 className="text-2xl mt-10 text-center">小さな感謝を伝えよう</h1>
            <div className="group w-[500px]">
              <div className="group flex mt-5"><TextareaAutosize  placeholder="コードの修正ありがとう！" className="border rounded-md border-gray-300 outline-none py-2 p-3 resize-none overflow-hidden w-full" minRows={1}></TextareaAutosize></div>
            </div>
            <button className="w-[100px] mt-7 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">送信</button>
          </div>
        </div>
        
      </main>
    </div>
  )
}

export default Home
