import type { NextPage } from 'next'
import Head from 'next/head'
import TextareaAutosize from 'react-textarea-autosize';


const Message: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen">
        <div className="flex justify-center">
          <div className="flex flex-col justify-center items-center">
            <h1 className="text-2xl mt-10 text-center">コードの修正ありがとう</h1>
            <div className="flex flex-row justify-center items-center">
                <button className="w-[80px] text-2xl mt-7 bg-blue-300 hover:bg-blue-400 text-white font-bold py-2 px-4 rounded-full">👍</button>
                <button className="ml-2  text-2xl w-[80px] mt-7 bg-blue-300 hover:bg-blue-400 text-white font-bold py-2 px-4 rounded-full">😁</button>
                <button className="ml-2 text-2xl w-[80px] mt-7 bg-blue-300 hover:bg-blue-400 text-white font-bold py-2 px-4 rounded-full">🙏</button>
            </div>
          </div>
        </div>
        
      </main>
    </div>
  )
}

export default Message
